environment: prod
source_name: open_meteo

bronze_path: data/prod/bronze
silver_path: data/prod/silver
gold_path: data/prod/gold

postgres_host: host.docker.internal
postgres_port: 5432
postgres_database: weather_dev
postgres_user: weather_user
postgres_table: daily_weather_summary_prod